import express from "express";
import { Adduseraddress, Deleteuseraddress, Edituseraddress, Getuseraddress } from "../controllers/Adduseraddress.js";
import { Addcar, Deletecar, Editcar, Getcar } from "../controllers/Addusercar.js";
import { logout,driverregister, driverregister2, driverlogin, phonelogin } from "../controllers/auth.js";
import { Allmessage, Message, Responce } from "../controllers/Customersupport.js";
import { driverbookings, Driverdata, Driverstatus, startedride } from "../controllers/Driverdates.js";
import { Getbookingstatus } from "../controllers/Getbookingstatus.js";
import { editdriveraccount, getdriverbyaccount, getdriverbymobile, getdrivers, getdriverslocation, searchDrivers } from "../controllers/getdrivers.js";
import { Editresponce, Getfilterrequests, Getrequests, Getrequestsdriver, Requestdriver } from "../controllers/Requestdriver.js";
import { AcceptRide, Getimages, UploadRideImages } from "../controllers/Ride.js";
import { Getbookingdetails, Getsharedrides, Shareride, Updatedriverlocation, Updateuserlocation } from "../controllers/Sharedrides.js";
import { Editprofile, Getprofile, Getusers } from "../controllers/Userprofilr.js";

const router = express.Router();
router.post("/driverregister", driverregister);
router.post("/driverregister2", driverregister2);
router.post("/driverlogin", driverlogin);
router.post("/logout", logout);
router.post("/getdrivers", getdrivers);
router.post("/searchdrivers", searchDrivers);
router.post("/addusercar", Addcar);
router.post("/getusercar", Getcar);
router.post("/editusercar", Editcar);
router.post("/deletecar", Deletecar);
router.post("/adduseraddress", Adduseraddress);
router.post("/getuseraddress", Getuseraddress);
router.post("/edituseraddress", Edituseraddress);
router.post("/deleteuseraddress", Deleteuseraddress);
router.post("/requestdriver", Requestdriver);
router.post("/getrequests", Getrequests);
router.post("/getrequestsdriver", Getrequestsdriver);
router.post("/editrequestresponce", Editresponce);
router.post("/getdriverslocation", getdriverslocation);
router.post("/getbookingstatus", Getbookingstatus);
router.post("/getdriverbookings", driverbookings);
router.post("/acceptrides", Driverstatus);
router.post("/driverdata", Driverdata);
router.post("/acceptride", AcceptRide);
router.post("/uploadcarimages", UploadRideImages);
router.post("/getimages", Getimages);
router.post("/phonelogin", phonelogin);
router.post("/editprofile", Editprofile);
router.post("/getprofile", Getprofile);
router.post("/getfilterrequests", Getfilterrequests);
router.post("/getusers", Getusers);
router.post("/getsharedrides", Getsharedrides);
router.post("/shareride", Shareride);
router.post("/updateuserlocation", Updateuserlocation);
router.post("/updatedriverlocation", Updatedriverlocation);
router.post("/getbookingdetails", Getbookingdetails);
router.post("/sendmessage", Message);
router.post("/sendresponce", Responce);
router.post("/allmessages", Allmessage);
router.post("/getdriverbymobile", getdriverbymobile);
router.post("/getdriverbyaccount", getdriverbyaccount);
router.post("/editdriveraccount", editdriveraccount);
router.post("/startedride", startedride);

export default router;
